name: Gadgets
version: '${version}'
main: me.diligord.gadgets.Gadgets
api-version: 1.19
commands:
  grapplebow:
    description: Gives a golf club.
    usage: /<command>
  glide:
    description: Enables gliding (elytra-like) mode.
    usage: /<command>